name: CD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - uses: actions/cache@v2
        with:
          path: dist
          key: ${{ github.sha	}}
      - run: pnpm install
      - run: pnpm build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v2
        with:
          path: dist
          key: ${{ github.sha	}}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
          registry-url: https://npm.pkg.github.com/
      - uses: actions/cache@v2
        with:
          path: dist
          key: ${{ github.sha	}}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  docgen:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - uses: actions/cache@v2
        with:
          path: docs
          key: ${{ github.sha	}}
      - run: pnpm install
      - run: pnpm docgen

  gh-pages:
    runs-on: ubuntu-latest
    needs: docgen
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: docs
          key: ${{ github.sha	}}
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
