name: CI

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test

  lint-code-style:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint:code-style
